name: Flutter APK Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for flutter scripts
      run: chmod +x ./flutter/bin/flutter
    - name: Get flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.0'
    - name: Run flutter pub get
      run: ./flutter/bin/flutter pub get
    - name: Build APK Release
      run: ./flutter/bin/flutter build apk --release
    - name: Upload APK to GitHub Release
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter/release/app-release.apk